Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 30
