version: '3.1'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '23306:3306'
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=electron
      - MYSQL_USER=electron_user
      - MYSQL_PASSWORD=electron

  mailcatcher:
    image: tophfr/mailcatcher
    restart: always
    ports:
      - '23080:80'

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -b '0.0.0.0'
    entrypoint: /app/docker-entrypoint.sh
    environment:
      - MAILER_HOST=mailcatcher
      - MAILER_PORT=25
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=electron
      - CONFIRMATION_URI=https://localhost:5000/#/portal/register/confirmation
      - RESET_PASSWORD_URI=https://localhost:5000/#/portal/forgot-password/reset-form
      - CHANGE_ETH_ADDRESS_CONFIRMATION_URI=https://localhost:5000/#/portal/dashboard
      - PRICEFEED_URL=http://neutron_pricefeed:4001/graphql
      - BLOCKCHAIN_URL=$BLOCKCHAIN_URL
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
      - temp_data:/app/tmp
    ports:
      - '23000:3000'
    links:
      - mailcatcher:mailcatcher
      - mysql:mysql
    networks:
      default:
      electron:

networks:
  electron:
    # Required to communicate with test_pricefeed
    # docker network create electron
    external: true

volumes:
  db:
  bundler_gems:
  temp_data:
