version: '3.1'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '23306:3306'
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=electron
      - MYSQL_USER=electron_user
      - MYSQL_PASSWORD=electron

  mailcatcher:
    image: tophfr/mailcatcher
    restart: always
    ports:
      - '23080:80'

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -b '0.0.0.0'
    environment:
      - MAILER_HOST=mailcatcher
      - MAILER_PORT=25
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=electron
      - CONFIRMATION_URI=https://localhost:5000/#/portal/register/confirmation
      - RESET_PASSWORD_URI=https://localhost:5000/#/portal/forgot-password/reset-form
      - MAILTRAP_USERNAME=$MAILTRAP_USERNAME
      - MAILTRAP_PASSWORD=$MAILTRAP_PASSWORD
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
    ports:
      - '23000:3000'
    links:
      - mailcatcher:mailcatcher
      - mysql:mysql

volumes:
  db:
  bundler_gems:
