default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000
  username: electron_user
  password: electron

development:
  <<: *default
  database: electron_dev

test:
  <<: *default
  database: electron_test

production:
  <<: *default
  database: electron_prod
