default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000
  host: <%= ENV.fetch("DB_HOST") { 'mysql' } %>
  port: <%= ENV.fetch("DB_PORT") { 3306 } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'electron' } %>

development:
  <<: *default
  database: electron_dev

test:
  <<: *default
  database: electron_test

production:
  <<: *default
  database: electron_prod
