common: &default_settings
  license_key: <PASTE LICENSE KEY HERE>
  app_name: Electron Core
  log_level: info
  # To disable the agent regardless of other settings, uncomment the following:
  # agent_enabled: false

development:
  <<: *default_settings
  app_name: Electron Core (Development)

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: Electron Core (Staging)

production:
  <<: *default_settings
