common: &default_settings
  license_key: <%= ENV.fetch("NEW_RELIC_LICENSE_KEY") { '' } %>
  app_name: Electron Core
  log_level: info

development:
  <<: *default_settings
  app_name: Electron Core (Development)

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  license_key: <%= ENV.fetch("NEW_RELIC_LICENSE_KEY") %>
  app_name: <%= ENV.fetch("NEW_RELIC_APP_NAME")  %>
